2025-03-17 10:20:39,528 INFO    MainThread:55100 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-17 10:20:39,529 INFO    MainThread:55100 [wandb_setup.py:_flush():67] Configure stats pid to 55100
2025-03-17 10:20:39,529 INFO    MainThread:55100 [wandb_setup.py:_flush():67] Loading settings from /Users/parasmukati/.config/wandb/settings
2025-03-17 10:20:39,529 INFO    MainThread:55100 [wandb_setup.py:_flush():67] Loading settings from /Users/parasmukati/DA6401/wandb/settings
2025-03-17 10:20:39,529 INFO    MainThread:55100 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-17 10:20:39,529 INFO    MainThread:55100 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/parasmukati/DA6401/wandb/run-20250317_102039-p4itv66e/logs/debug.log
2025-03-17 10:20:39,529 INFO    MainThread:55100 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/parasmukati/DA6401/wandb/run-20250317_102039-p4itv66e/logs/debug-internal.log
2025-03-17 10:20:39,529 INFO    MainThread:55100 [wandb_init.py:init():761] calling init triggers
2025-03-17 10:20:39,529 INFO    MainThread:55100 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'wandb_project': 'myprojectname', 'wandb_entity': 'myname', 'dataset': 'fashion_mnist', 'epochs': 10, 'batch_size': 32, 'loss': 'cross_entropy', 'optimizer': 'adam', 'learning_rate': 0.001, 'momentum': 0.9, 'beta': 0.9, 'beta1': 0.9, 'beta2': 0.999, 'num_layers': 2, 'hidden_size': 128, 'activation': 'ReLU', 'weight_init': 'Xavier', '_wandb': {}}
2025-03-17 10:20:39,530 INFO    MainThread:55100 [wandb_init.py:init():784] starting backend
2025-03-17 10:20:39,530 INFO    MainThread:55100 [wandb_init.py:init():788] sending inform_init request
2025-03-17 10:20:39,580 INFO    MainThread:55100 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-03-17 10:20:39,580 INFO    MainThread:55100 [wandb_init.py:init():798] backend started and connected
2025-03-17 10:20:39,585 INFO    MainThread:55100 [wandb_init.py:init():891] updated telemetry
2025-03-17 10:20:39,585 INFO    MainThread:55100 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-17 10:20:43,858 ERROR   MainThread:55100 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 963, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403: {"data":{"upsertBucket":null},"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}]}
2025-03-17 10:20:44,857 INFO    MsgRouterThr:55100 [mailbox.py:close():129] Closing mailbox, abandoning 0 handles.
